'use strict';
let trackerPending=null,trackerAccounts=null,trackerFailure=false,trackerOwner='',trackerPool='',trackerQuery='',trackerPage=0,pullDraft=null,pullOriginal=undefined;
const poolNames=()=>({1:tr('Résonateurs en vedette','Featured Resonators'),2:tr('Armes en vedette','Featured weapons'),3:tr('Résonateurs permanents','Standard Resonators'),4:tr('Armes permanentes','Standard weapons'),5:tr('Débutant','Beginner'),6:tr('Débutant au choix','Beginner choice'),8:tr('Nouveau voyage · Résonateurs','New voyage · Resonators'),9:tr('Nouveau voyage · armes','New voyage · weapons'),10:tr('Collaboration · Résonateurs','Collaboration · Resonators'),11:tr('Collaboration · armes','Collaboration · weapons'),12:tr('Réverbération · Résonateurs','Reverb · Resonators'),13:tr('Réverbération · armes','Reverb · weapons')});
async function loadTracker(){try{trackerAccounts=await PullStore.all();trackerFailure=false;}catch{trackerFailure=true;}if(currentView==='more'&&moreTab==='tracker')render();}
function pullPlannerHTML(){
 const s=CompanionStore.get(),p=pullDraft||s.settings.pullBudget||{characters:1,weapons:0,characterPity:null,weaponPity:null,guaranteed:null};
 if(pullOriginal===undefined)pullOriginal=structuredClone(s.settings.pullBudget||null);
 const field=(name,label,min,max)=>`<label>${label}<input name="${name}" type="number" step="1" min="${min}" max="${max}" value="${p[name]??''}" placeholder="?"></label>`;
 return companionPanel(tr('Budget d’invocations','Convene budget'),`<p>${tr('Bannières régulières en vedette uniquement. Indique les copies supplémentaires souhaitées. Les monnaies proviennent de ton inventaire.','Regular featured banners only. Enter the additional copies you want. Currencies come from your inventory.')}</p><form id="pullBudgetForm" class="companion-form">${field('characters',tr('Copies de Résonateur à obtenir','Resonator copies to obtain'),0,7)}${field('weapons',tr('Copies d’arme à obtenir','Weapon copies to obtain'),0,5)}${field('characterPity',tr('Compteur Résonateur actuel (0–79)','Current Resonator pity (0–79)'),0,79)}${field('weaponPity',tr('Compteur arme actuel (0–79)','Current weapon pity (0–79)'),0,79)}<label>${tr('Prochain Résonateur 5★ garanti en vedette','Next 5★ Resonator guaranteed featured')}<select name="guaranteed"><option value="" ${p.guaranteed===null?'selected':''}>?</option><option value="true" ${p.guaranteed===true?'selected':''}>${tr('Oui','Yes')}</option><option value="false" ${p.guaranteed===false?'selected':''}>${tr('Non · 50/50','No · 50/50')}</option></select></label><div class="companion-actions wide"><button class="companion-button">${tr('Calculer et enregistrer','Calculate and save')}</button>${companionButton('cancel-pull-budget',tr('Annuler les changements','Cancel changes'))}${companionButton('pull-wallet',tr('Renseigner mes monnaies','Record my currencies'))}</div></form><div id="pullBudgetResult">${pullBudgetResult(s.settings.pullBudget)}</div>`);
}
function pullBudgetResult(p){
 if(!p)return '';
 const char=ConveneRules.budget(p.characters,p.characterPity,p.guaranteed),weapon=ConveneRules.budget(p.weapons,p.weaponPity,true,true),wallet=CompanionStore.get().resources;
 const astro=wallet['3']??null,radiant=wallet['50002']??null,forging=wallet['50005']??null;
 const cost=ConveneRules.astrites(char.max,weapon.max,radiant,forging);
 return `<div class="budget-grid">${[[tr('Minimum théorique','Theoretical minimum'),char.min,weapon.min],[tr('Somme des médianes du modèle','Sum of model medians'),char.median,weapon.median],[tr('Maximum garanti','Guaranteed maximum'),char.max,weapon.max]].map(([label,c,w])=>`<article><h3>${label}</h3><b>${c+w}</b><p>${c} ${tr('Résonateur','Resonator')} + ${w} ${tr('arme','weapon')}</p></article>`).join('')}</div><p>${tr('Astrites','Astrites')} : ${astro??'?'} · ${tr('Marées radieuses','Radiant Tides')} : ${radiant??'?'} · ${tr('Marées de forge','Forging Tides')} : ${forging??'?'}</p><p>${tr('Astrites nécessaires au scénario maximal après les marées disponibles','Astrites needed for the maximum scenario after available Tides')} : <b>${cost??'?'}</b> · ${tr('Reste à obtenir','Still needed')} : <b>${cost===null||astro===null?'?':Math.max(0,cost-astro)}</b></p><p class="companion-note">${tr('Une Astrite ne finance qu’une seule réserve : aucun double comptage entre personnage et arme. Le minimum suppose des 5★ immédiats. Le modèle médian utilise 0,8 % par tirage et la garantie au 80e, sans soft pity ; ce n’est pas la probabilité réelle du jeu. Un compteur inconnu est traité comme 0 uniquement pour ce scénario prudent ; une garantie inconnue comme un 50/50.','Astrites are shared once between character and weapon budgets. The minimum assumes immediate 5★ drops. The median model uses 0.8% per pull and hard pity at 80, without soft pity; it is not the actual game probability. Unknown pity is treated as 0 only for this conservative scenario; an unknown guarantee as a 50/50.')}</p><p class="companion-note"><a href="https://www.prydwen.gg/wuthering-waves/guides/gacha" target="_blank" rel="noopener">${tr('Règles consultées le 13/09/2026','Rules checked 2026-09-13')} · Prydwen</a></p>`;
}
function trackerHTML(){
 if(trackerAccounts===null&&!trackerFailure)queueMicrotask(loadTracker);
 const accounts=trackerAccounts||[],account=accounts.find(a=>a.owner===trackerOwner)||accounts[0];if(account)trackerOwner=account.owner;
 const rows=(account?.rows||[]).filter(r=>(!trackerPool||r.pool===Number(trackerPool))&&(!trackerQuery||(r.name+' '+r.id).toLowerCase().includes(trackerQuery.toLowerCase()))),pages=Math.max(1,Math.ceil(rows.length/40));trackerPage=Math.min(trackerPage,pages-1);
 return companionPanel(tr('Importer WuWa Tracker','Import WuWa Tracker'),`<p>${tr('Choisis ExportProfile ou ExportPullHistory depuis les réglages de WuWa Tracker. Seuls les exports JSON nettoyés sont acceptés. N’utilise pas de journal du jeu, lien d’authentification ou token.','Choose ExportProfile or ExportPullHistory from WuWa Tracker settings. Only sanitized JSON exports are accepted. Do not use game logs, authentication links or tokens.')}</p><div class="companion-actions"><label class="companion-button companion-file">${tr('Choisir un export JSON','Choose a JSON export')}<input type="file" id="trackerFile" accept="application/json,.json"></label>${companionButton('export-pulls',tr('Exporter tous mes historiques','Export all my histories'))}${trackerFailure?companionButton('retry-pulls',tr('Réessayer le stockage','Retry storage')):''}</div><p class="companion-note">${tr('Les historiques restent sur cet appareil, séparés de la sauvegarde du compte. Pour changer d’appareil, exporte les deux fichiers. Aucun inventaire, niveau ou équipement n’est déduit des invocations.','Histories stay on this device, separate from the account backup. Export both files when switching devices. No inventory, levels or equipment are inferred from pulls.')}</p><div id="trackerPreview" aria-live="polite">${trackerPreviewHTML()}</div>`)+
 companionPanel(tr('Historique des invocations','Convene history'),`${trackerFailure?`<p class="companion-error">${tr('Le stockage des historiques est indisponible. Aucun import n’est enregistré.','History storage is unavailable. No import has been saved.')}</p>`:''}<form id="trackerFilter" class="companion-form"><label>${tr('Profil source','Source profile')}<select name="owner">${accounts.map(a=>`<option value="${esc(a.owner)}" ${a.owner===trackerOwner?'selected':''}>${esc(a.owner)}</option>`).join('')}</select></label><label>${tr('Catégorie','Category')}<select name="pool"><option value="">${tr('Toutes','All')}</option>${[...new Set(account?.rows.map(r=>r.pool)||[])].sort((a,b)=>a-b).map(p=>`<option value="${p}" ${String(p)===trackerPool?'selected':''}>${esc(poolNames()[p]||'#'+p)}</option>`).join('')}</select></label><label>${tr('Rechercher','Search')}<input name="query" type="search" value="${esc(trackerQuery)}"></label><button class="companion-button">${tr('Filtrer','Filter')}</button></form><p>${rows.length} ${tr('invocations','pulls')} · ${rows.filter(r=>r.quality===5).length} × 5★ · ${rows.filter(r=>r.quality===4).length} × 4★</p>${trackerPityHTML(account)}<div class="companion-list">${rows.slice(trackerPage*40,trackerPage*40+40).map(r=>`<article class="companion-card"><span class="resource-symbol">${r.quality}★</span><div><b>${esc(r.name)}</b><small>${esc(poolNames()[r.pool]||'#'+r.pool)} · ${esc(new Date(r.time).toLocaleString(lang))}${r.id===null?' · '+tr('identifiant inconnu','unknown ID'):''}</small></div></article>`).join('')||`<p>${tr('Aucune invocation à afficher.','No pulls to display.')}</p>`}</div><div class="companion-actions">${trackerPage?companionButton('tracker-page',tr('Précédent','Previous'),String(trackerPage-1)):''}<span>${trackerPage+1} / ${pages}</span>${trackerPage+1<pages?companionButton('tracker-page',tr('Suivant','Next'),String(trackerPage+1)):''}</div>`)+pullPlannerHTML();
}
function trackerPityHTML(account){
 if(!account?.rows.length)return '';
 const list=[1,2].filter(pool=>account.rows.some(r=>r.pool===pool)).map(pool=>{const p=ConveneRules.pity(account.rows,pool);return `<li>${esc(poolNames()[pool])} : ${p.max===null?'≥ '+p.min:p.min===p.max?p.min:p.min+'–'+p.max}</li>`;}).join('');
 return `<p class="companion-note">${tr('Compteurs observés à la fin de l’export','Counters observed at the end of the export')} (${esc(new Date(account.rows[0].time).toLocaleDateString(lang))}) :</p><ul>${list}</ul><p class="companion-note">${tr('Un intervalle indique un ordre inconnu dans un tirage multiple. Sans 5★ présent, seule une borne minimale est connue. Des périodes absentes peuvent rendre ces compteurs incomplets ; ils ne remplacent jamais automatiquement les compteurs actuels du budget.','A range means order within a multi-pull is unknown. Without a recorded 5★, only a lower bound is known. Missing periods may leave counters incomplete; these never automatically replace current budget counters.')}</p>`;
}
function trackerPreviewHTML(){
 const p=trackerPending;if(!p)return '';
 if(p.data.kind==='history')return `<p>${p.data.accounts.reduce((n,a)=>n+a.rows.length,0)} ${tr('invocations lues','pulls read')} · ${p.added} ${tr('nouvelles invocations après fusion','new pulls after merging')} · ${p.data.accounts.length} ${tr('profils séparés','separate profiles')}</p>${companionButton('apply-tracker',tr('Fusionner cet historique','Merge this history'))}${companionButton('cancel-tracker',tr('Annuler','Cancel'))}`;
 return `<p>${Object.keys(p.data.resources).length} ${tr('stocks','stock records')} · ${Object.keys(p.data.achievements).length} ${tr('succès terminés','completed achievements')} · ${p.conflicts} ${tr('valeurs différentes déjà renseignées','different values already recorded')}</p><p>${p.data.ignoredPlans} ${tr('objectifs Tracker non transférés : leur progression initiale ne prouve pas le compte actuel.','Tracker plans not transferred: their starting progress does not establish the current account.')}</p><details><summary>${tr('Examiner les valeurs proposées','Review proposed values')}</summary><div class="import-values">${Object.entries(p.data.resources).map(([id,n])=>`<p>${esc(materialName(id))} : ${p.before.resources[id]??'?'} → ${n}</p>`).join('')}${Object.keys(p.data.achievements).map(id=>`<p>${tr('Succès','Achievement')} #${esc(id)} : ${esc(p.before.achievements[id]||'?')} → ${tr('terminé','done')}</p>`).join('')}</div></details><label class="plan-passive"><input type="checkbox" id="trackerReplace">${tr('Remplacer aussi les valeurs déjà renseignées qui diffèrent','Also replace previously recorded values that differ')}</label>${companionButton('apply-tracker',tr('Importer les données proposées','Import proposed data'))}${companionButton('cancel-tracker',tr('Annuler','Cancel'))}`;
}
moreViews.tracker=trackerHTML;
Object.assign(companionActions,{
 'tracker-page':value=>{trackerPage=Number(value);render();},'retry-pulls':loadTracker,
 'cancel-pull-budget':()=>{pullDraft=null;pullOriginal=undefined;render();},
 'pull-wallet':()=>{currentView='account';accountTab='resources';resourceQuery='';resourceFilter='currency';resourcePage=0;render();},
 'export-pulls':async()=>companionDownload({format:'wuwa-companion-pulls',version:1,createdAt:new Date().toISOString(),accounts:await PullStore.all()},'wuwa-companion-pulls-'+new Date().toISOString().slice(0,10)+'.json'),
 'cancel-tracker':()=>{trackerPending=null;render();},
 'apply-tracker':async()=>{
  const p=trackerPending;if(!p||p.busy)return;p.busy=true;
  try{if(p.data.kind==='history'){await PullStore.merge(p.data.accounts);trackerAccounts=await PullStore.all();}
  else{const replace=document.getElementById('trackerReplace')?.checked;CompanionStore.update(s=>{
   for(const key of ['resources','achievements'])for(const [id,value]of Object.entries(p.data[key])){const old=p.before[key][id]??null;if(!replace&&old!==null&&old!=='unknown')continue;if((s[key][id]??null)!==old)throw Error('Record changed since preview');s[key][id]=value;}
  },tr('Import du profil WuWa Tracker · stocks et succès','WuWa Tracker profile import · stock and achievements'));}
  trackerPending=null;render();companionMessage(tr('Import enregistré.','Import saved.'));}finally{p.busy=false;}
 }
});
document.getElementById('view').addEventListener('change',async event=>{
 if(event.target.id!=='trackerFile')return;trackerPending=null;const file=event.target.files[0];if(!file)return;
 try{if(file.size>20*1024*1024)throw Error('size');const data=TrackerImport.parse(await file.text()),before=CompanionStore.get();let added=0,conflicts=0;
  if(data.kind==='history'){const all=await PullStore.all();for(const a of data.accounts){const old=all.find(x=>x.owner===a.owner)?.rows||[];added+=TrackerImport.merge(old,a.rows).length-old.length;}}
  else for(const key of ['resources','achievements'])for(const [id,value]of Object.entries(data[key]))if(before[key][id]!=null&&before[key][id]!=='unknown'&&before[key][id]!==value)conflicts++;
  trackerPending={data,before,added,conflicts};document.getElementById('trackerPreview').innerHTML=trackerPreviewHTML();
 }catch{document.getElementById('trackerPreview').textContent=tr('Export incompatible, données invalides, informations d’authentification présentes ou stockage indisponible. Aucune donnée modifiée.','Incompatible export, invalid data, authentication information present or storage unavailable. No data changed.');}
});
function readPullBudget(form){const data=new FormData(form),p={};for(const k of ['characters','weapons','characterPity','weaponPity'])p[k]=data.get(k)===''?null:Number(data.get(k));p.guaranteed=data.get('guaranteed')===''?null:data.get('guaranteed')==='true';return p;}
document.getElementById('view').addEventListener('input',e=>{if(e.target.form?.id==='pullBudgetForm')pullDraft=readPullBudget(e.target.form);});
document.getElementById('view').addEventListener('submit',e=>{
 if(e.target.id==='trackerFilter'){e.preventDefault();const d=new FormData(e.target);trackerOwner=d.get('owner');trackerPool=d.get('pool');trackerQuery=d.get('query').trim();trackerPage=0;render();}
 if(e.target.id==='pullBudgetForm'){e.preventDefault();try{const p=readPullBudget(e.target);ConveneRules.budget(p.characters,p.characterPity,p.guaranteed);ConveneRules.budget(p.weapons,p.weaponPity,true,true);CompanionStore.update(s=>{if(JSON.stringify(s.settings.pullBudget||null)!==JSON.stringify(pullOriginal))throw Error('Budget changed');s.settings.pullBudget=p;});pullDraft=null;pullOriginal=structuredClone(p);document.getElementById('pullBudgetResult').innerHTML=pullBudgetResult(p);}catch{companionMessage(tr('Vérifie les nombres, les compteurs ou une modification dans un autre onglet. Annule les changements pour recharger.','Check counts, pity or a change in another tab. Cancel changes to reload.'),true);}}
});
