'use strict';
let recommendationData=null,recommendationError=false,recommendationLoading=false;
async function loadRecommendations(){
 if(recommendationLoading||recommendationData)return;recommendationLoading=true;
 try{const data=await fetchJSON('./data/recommendations.json');if(data.schema!==1||!Array.isArray(data.profiles))throw Error('Invalid recommendations');recommendationData=data;recommendationError=false;}
 catch{recommendationError=true;}finally{recommendationLoading=false;}
 if(document.getElementById('detail').open&&['build','teams'].includes(profileTab))renderProfileSection();
}
const recommendationContexts=new Map();
function recommendationFor(id){const base=recommendationData?.profiles.find(p=>p.characterId===id);if(!base)return null;const choice=base.variants?.[recommendationContexts.get(id)-1];return choice?{...base,...choice,stats:{...base.stats,...choice.stats}}:base;}
function recommendationContextHTML(id){const base=recommendationData?.profiles.find(p=>p.characterId===id);if(!base?.variants?.length)return '';return '<nav class="section-tabs" aria-label="'+tr('Contexte du build','Build context')+'">'+[base,...base.variants].map((v,i)=>companionButton('recommendation-context',localText(v.context),id+'|'+i).replace('<button ','<button aria-pressed="'+((recommendationContexts.get(id)||0)===i)+'" ')).join('')+'</nav>';}
function recommendationHTML(row){
 if(!recommendationData&&!recommendationError)queueMicrotask(loadRecommendations);
 const profile=recommendationFor(row.id);
 if(!profile)return `<h3>${tr('Recommandation Companion','Companion recommendation')}</h3>${recommendationContextHTML(row.id)}<p>${recommendationLoading?tr('Chargement…','Loading…'):tr('Aucune recommandation vérifiée n’est encore disponible pour ce Résonateur. Tu peux créer ton profil personnel.','No reviewed recommendation is available for this Resonator yet. You can create a personal profile.')}</p>${recommendationError?companionButton('recommendations-retry',tr('Réessayer','Retry')):''}`;
 const owned=CompanionStore.get().weapons;
 return `<section class="recommendation"><h3>${tr('Recommandation Companion','Companion recommendation')}</h3>${recommendationContextHTML(row.id)}<p>${esc(localText(profile.context))}</p><p>${esc(localText(profile.notes))}</p><h4>${tr('Armes — ordre général','Weapons — general order')}</h4><p class="companion-note">${tr('L’ordre ne dépend pas de ton inventaire. Les rangs indiqués sont ceux du guide ; un autre rang peut changer la comparaison.','Order is independent of your inventory. Ranks are those used by the guide; a different rank may change the comparison.')}</p><ol class="weapon-ranking">${profile.weapons.map(([name,rank])=>{const w=WEAPONS.find(w=>w.name===name&&w.type===row.weapon);return `<li><b>${esc(name)}</b> <span>R${rank}</span>${w&&owned.some(c=>c.catalogId===w.id)?`<small>${tr('Présente dans ton inventaire','In your inventory')}</small>`:''}</li>`;}).join('')}</ol><h4>${tr('Échos & statistiques','Echoes & stats')}</h4><p>${profile.setPieces||5}P ${profile.sets.map(esc).join(' / ')}${profile.secondarySets?' + 2P '+profile.secondarySets.map(esc).join(' / '):''}${profile.tertiarySets?' + 2P '+profile.tertiarySets.map(esc).join(' / '):''} · ${profile.echoes.map(esc).join(' / ')}</p><dl class="profile-stats">${Object.entries(profile.stats).map(([key,values])=>`<div><dt>${key.startsWith('main4')?'4':key==='main1'?'1':'3'} ${tr('coûts','cost')}</dt><dd>${values.map(statLabel).map(esc).join(' / ')}</dd></div>`).join('')}</dl><p>${tr('Sous-statistiques','Substats')} : ${profile.substats.map(statLabel).map(esc).join(' → ')}</p><p>${tr('Recharge indicative, selon la rotation','Indicative energy, depending on rotation')} : ${esc(profile.energy)}</p><h4>${tr('Priorité des compétences','Skill priority')}</h4><p>${profile.priority.map(k=>esc(SKILL_LABELS[lang][k])).join(' → ')}</p><div class="companion-actions">${CompanionStore.get().roster?.includes(row.id)?companionButton('recommendation-priorities',tr('Préparer ces priorités dans mon objectif','Prepare these priorities in my goal'),row.id):''}${companionButton('recommendation-copy',tr('Personnaliser ce build','Customize this build'),row.id)}</div><p class="companion-note">${tr('Vérifié le','Checked on')} ${recommendationData.checkedAt} · ${tr('version de référence','reference version')} ${esc(recommendationData.gameVersion)} · ${profile.sources.map((url,i)=>`<a href="${esc(url)}" target="_blank" rel="noopener">${new URL(url).hostname.includes('prydwen')?'Prydwen':'Game8'}</a>`).join(' · ')}. ${tr('Repères de guide, pas une simulation des dégâts de ton compte.','Guide references, not a damage simulation of your account.')}</p></section>`;
}
function recommendationTeamsHTML(row){const p=recommendationFor(row.id);if(!recommendationData&&!recommendationError)queueMicrotask(loadRecommendations);if(!p?.teams?.length)return '';const s=CompanionStore.get();return `<h3>${tr('Compositions de référence','Reference teams')}</h3>${p.teams.map((members,i)=>`<p>${members.map(id=>esc(characterName(id))+(s.roster?.includes(id)?' ✓':'')).join(' · ')}</p>${members.every(id=>s.roster?.includes(id))?companionButton('use-recommended-team',tr('Préparer cette équipe','Prepare this team'),row.id+'|'+i):`<p class="companion-note">${tr('Tous les membres doivent être possédés pour enregistrer cette équipe.','All members must be owned to save this team.')}</p>`}`).join('')}<p class="companion-note">${p.sources.map(url=>`<a href="${esc(url)}" target="_blank" rel="noopener">${tr('Guide de référence','Reference guide')}</a>`).join(' · ')}</p>`;}
Object.assign(companionActions,{
 'recommendation-context':value=>{const [id,n]=value.split('|');recommendationContexts.set(id,Number(n));renderProfileSection();[...document.querySelectorAll('[data-action="recommendation-context"]')].find(b=>b.dataset.value===value)?.focus();},
 'recommendations-retry':()=>{recommendationError=false;return loadRecommendations();},
 'recommendation-priorities':id=>{const p=recommendationFor(id),s=CompanionStore.get();if(!p||!s.roster?.includes(id))return;const original=s.goals[id]||null;if(!goalOriginals.has(id))goalOriginals.set(id,structuredClone(original));const goal=goalDrafts.get(id)||structuredClone(original)||{level:null,skills:{},priorities:{},forteNodes:{}};goal.priorities=Object.fromEntries(p.priority.map((k,i)=>[k,i<2?3:i<3?2:1]));goalDrafts.set(id,goal);closeDialog('detail');planningCharacter=id;currentView='planner';render();companionMessage(tr('Priorités préparées. Choisis les niveaux puis enregistre ton objectif.','Priorities prepared. Choose levels, then save your goal.'));},
 'recommendation-copy':async id=>{await loadExtended('echo');if(profileSelection?.id!==id||!document.getElementById('detail').open)return;const p=recommendationFor(id);if(!p)return;const c=DATA.find(c=>c.id===id),w=WEAPONS.find(w=>w.name===p.weapons[0][0]&&w.type===c.weapon),echo=extendedCatalog.echo.find(e=>p.echoes.includes(e.name)&&e.sets.some(s=>[...p.sets,...(p.secondarySets||[]),...(p.tertiarySets||[])].includes(s.name))),allSets=extendedCatalog.echo.flatMap(e=>e.sets),set=allSets.find(s=>p.sets.includes(s.name));buildOriginal=null;buildDraft={id:crypto.randomUUID(),characterId:id,name:tr('Mon build','My build'),role:p.role,context:localText(p.context),notes:localText(p.notes),weaponId:w?.id||null,echoId:echo?.id||null,setId:set?.id||null,setPieces:p.setPieces||5,secondarySetId:allSets.find(s=>p.secondarySets?.includes(s.name))?.id||null,tertiarySetId:allSets.find(s=>p.tertiarySets?.includes(s.name))?.id||null,costPattern:p.stats.main4b?'44111':'43311',stats:Object.fromEntries(Object.entries(p.stats).map(([k,v])=>[k,v[0]||null])),substats:[...p.substats]};renderProfileSection();document.getElementById('buildForm')?.scrollIntoView({block:'start'});},
 'use-recommended-team':value=>{const [id,index]=value.split('|'),p=recommendationFor(id),members=p?.teams[Number(index)];if(!members||!members.every(id=>CompanionStore.get().roster?.includes(id)))return;teamOriginal=null;teamDraft={id:crypto.randomUUID(),name:characterName(id),members:[...members],favorite:false,builds:{}};closeDialog('detail');moreTab='teams';currentView='more';render();}
});
