'use strict';
let teamDraft=null,teamOriginal=null,teamQuery='',onlyFavoriteTeams=false;
let buildDraft=null,buildOriginal=null;
const buildStatSlots=b=>(b.costPattern==='44111'?[['main4',4],['main4b',4],['main1',1]]:[['main4',4],['main3',3],['main3b',3],['main1',1]]);
function characterName(id){return DATA.find(c=>c.id===id)?.name||id;}
function teamsPage(){
 const s=CompanionStore.get(),draft=teamDraft||{id:crypto.randomUUID(),name:'',members:['','',''],favorite:false,builds:{}};
 const teams=s.teams.filter(t=>(!onlyFavoriteTeams||t.favorite)&&(t.name+' '+t.members.map(characterName).join(' ')).toLocaleLowerCase().includes(teamQuery.toLocaleLowerCase()));
 return companionPanel(tr('Mes équipes','My teams'),`<form id="teamSearch" class="companion-form"><label>${tr('Rechercher','Search')}<input name="query" type="search" value="${esc(teamQuery)}"></label><label class="check-label"><input name="favorites" type="checkbox" ${onlyFavoriteTeams?'checked':''}>${tr('Favoris uniquement','Favorites only')}</label><button class="companion-button">${tr('Filtrer','Filter')}</button></form>
 <div class="companion-list">${teams.map(t=>`<article class="team-card"><div class="echo-heading"><h3>${esc(t.name)}</h3><button type="button" class="companion-button" data-action="favorite-team" data-value="${esc(t.id)}" aria-pressed="${!!t.favorite}">${t.favorite?'★':'☆'} ${tr('Favori','Favorite')}</button></div><div class="team-members">${t.members.map(id=>{const c=DATA.find(c=>c.id===id),b=s.builds.find(b=>b.id===t.builds?.[id]);return `<div><button type="button" class="team-member" data-action="profile" data-value="character|${esc(id)}">${c?.image?`<img src="${esc(c.image)}" alt="" loading="lazy">`:'<span aria-hidden="true">◇</span>'}<b>${esc(characterName(id))}</b></button><small>${s.roster?.includes(id)?(b?esc(b.name):tr('Build général','General build')):tr('Résonateur retiré du compte','Resonator removed from account')}</small></div>`;}).join('')}</div><div class="companion-actions">${companionButton('edit-team',tr('Modifier','Edit'),t.id)}${companionButton('remove-team',tr('Retirer','Remove'),t.id)}</div></article>`).join('')||`<p>${tr('Crée une équipe avec trois Résonateurs possédés.','Create a team with three owned Resonators.')}</p>`}</div>`)+
 companionPanel(teamOriginal?tr('Modifier l’équipe','Edit team'):tr('Créer une équipe','Create a team'),`<form id="teamForm" class="companion-form"><label class="wide">${tr('Nom de l’équipe','Team name')}<input name="name" required maxlength="80" value="${esc(draft.name)}"></label>${draft.members.map((id,i)=>`<div class="team-slot"><label>${tr('Emplacement','Slot')} ${i+1}<select name="member:${i}" required><option value="">—</option>${DATA.filter(c=>s.roster?.includes(c.id)||c.id===id).map(c=>`<option value="${c.id}" ${id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>${tr('Profil de build','Build profile')}<select name="build:${i}"><option value="">${tr('Général','General')}</option>${s.builds.filter(b=>b.characterId===id).map(b=>`<option value="${b.id}" ${draft.builds?.[id]===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label></div>`).join('')}<label class="check-label"><input name="favorite" type="checkbox" ${draft.favorite?'checked':''}>${tr('Équipe favorite','Favorite team')}</label><div class="companion-actions wide"><button class="companion-button">${tr('Enregistrer l’équipe','Save team')}</button>${companionButton('cancel-team',tr('Annuler','Cancel'))}</div></form>`);
}
function readTeamForm(form){const f=new FormData(form),members=[0,1,2].map(i=>f.get('member:'+i));return {id:teamDraft?.id||crypto.randomUUID(),name:f.get('name').trim(),members,favorite:f.get('favorite')==='on',builds:Object.fromEntries(members.filter(Boolean).map(id=>[id,f.get('build:'+members.indexOf(id))||null]))};}
function buildField(label,key,options,value){return `<label>${label}<select name="${key}"><option value="">—</option>${options.map(([id,name])=>`<option value="${esc(id)}" ${value===id?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;}
function buildProfilesHTML(character){
 const s=CompanionStore.get(),profiles=s.builds.filter(b=>b.characterId===character.id);
 const list=`<h3>${tr('Mes profils de build','My build profiles')}</h3><div class="companion-list">${profiles.map(b=>`<article class="activity-card"><div><h3>${esc(b.name)}</h3><p>${esc(b.context)}</p><small>${esc(WEAPONS.find(w=>w.id===b.weaponId)?.name||b.weaponId||'—')} · ${buildStatSlots(b).map(([k])=>b.stats[k]).filter(Boolean).map(statLabel).map(esc).join(' · ')}</small><p class="source-description">${esc(b.notes)}</p></div><div class="companion-actions">${companionButton('edit-build',tr('Modifier','Edit'),b.id)}${companionButton('remove-build',tr('Retirer','Remove'),b.id)}</div></article>`).join('')||`<p>${tr('Un profil conserve tes choix pour un contexte ou une équipe. Il ne remplace pas ton équipement actuel.','A profile keeps your choices for a context or team. It does not replace your current equipment.')}</p>`}</div>${companionButton('new-build',tr('Créer un profil personnel','Create a personal profile'),character.id)}`;
 if(!buildDraft||buildDraft.characterId!==character.id)return list;
 const b=buildDraft;
 if(!extendedCatalog.echo.length&&!extendedCatalog.loading.echo&&!extendedCatalog.errors.echo)queueMicrotask(()=>loadExtended('echo'));
 const sets=[...new Map(extendedCatalog.echo.flatMap(e=>e.sets).map(s=>[s.id,s])).values()];
 const options=(rows,selected)=>{const result=rows.map(r=>[r.id,r.label||r.name]);if(selected&&!result.some(([id])=>id===selected))result.push([selected,tr('Référence conservée : ','Preserved reference: ')+selected]);return result;};
 return list+`<form id="buildForm" class="companion-form"><label>${tr('Nom du profil','Profile name')}<input name="name" maxlength="80" required value="${esc(b.name)}"></label><label>${tr('Contexte / équipe','Context / team')}<input name="context" maxlength="200" value="${esc(b.context)}"></label>${buildField(tr('Rôle','Role'),'role',[['dps',tr('Dégâts principaux','Main damage')],['hybrid',tr('Dégâts et soutien','Damage and support')],['support',tr('Soutien','Support')]],b.role)}
 <label class="wide">${tr('Arme (recherche dans le catalogue)','Weapon (search the catalogue)')}<input name="weapon" list="buildWeapons" value="${esc(b.weaponText??(b.weaponId?(WEAPONS.find(w=>w.id===b.weaponId)?.name||'')+' · #'+b.weaponId:''))}"><datalist id="buildWeapons">${WEAPONS.filter(w=>w.type===character.weapon).map(w=>`<option value="${esc(w.name+' · #'+w.id)}"></option>`).join('')}</datalist></label>
 ${buildField(tr('Pièces par ensemble','Pieces per set'),'setPieces',[['5','5'],['3','3 + 2'],['1','1 + 2 + 2']],String(b.setPieces??5))}${buildField(tr('Sonate principale','Primary Sonata'),'setId',options(sets,b.setId),b.setId)}${(b.setPieces??5)<5?buildField(tr('Deuxième Sonate (2 pièces)','Second Sonata (2 pieces)'),'secondarySetId',options(sets,b.secondarySetId),b.secondarySetId):''}${b.setPieces===1?buildField(tr('Troisième Sonate (2 pièces)','Third Sonata (2 pieces)'),'tertiarySetId',options(sets,b.tertiarySetId),b.tertiarySetId):''}${buildField(tr('Écho principal','Main Echo'),'echoId',options(extendedCatalog.echo,b.echoId),b.echoId)}
 ${buildField(tr('Répartition des coûts','Cost arrangement'),'costPattern',[['43311','4 · 3 · 3 · 1 · 1'],['44111','4 · 4 · 1 · 1 · 1']],b.costPattern||'43311')}
 ${buildStatSlots(b).map(([k,cost],i)=>buildField(tr('Statistique principale','Main stat')+' · '+cost+(i===2?' (2)':''),k,EchoRules.mainTypes(cost).map(k=>[k,statLabel(k)]),b.stats[k])).join('')}
 <fieldset class="wide build-substats"><legend>${tr('Sous-statistiques prioritaires (jusqu’à 5)','Priority substats (up to 5)')}</legend>${EchoRules.subTypes.map(k=>`<label class="check-label"><input type="checkbox" name="sub:${k}" ${b.substats.includes(k)?'checked':''}>${esc(statLabel(k))}</label>`).join('')}</fieldset>
 <label class="wide">${tr('Notes de rotation / conditions','Rotation notes / conditions')}<textarea name="notes" maxlength="2000">${esc(b.notes)}</textarea></label><div class="companion-actions wide"><button class="companion-button">${tr('Enregistrer le profil','Save profile')}</button>${companionButton('cancel-build',tr('Annuler','Cancel'))}</div></form>`;
}
function readBuildForm(form,validate=false){
 const f=new FormData(form),weapon=f.get('weapon'),id=weapon?weapon.slice(weapon.lastIndexOf(' · #')+4):null;
 const row=WEAPONS.find(w=>w.id===id);if(validate&&weapon&&weapon!==((row?.name||'')+' · #'+id))throw Error('Choose a catalogue weapon');
 return {...buildDraft,name:f.get('name').trim(),context:f.get('context').trim(),role:f.get('role'),weaponId:id,weaponText:weapon,echoId:f.get('echoId')||null,setId:f.get('setId')||null,setPieces:Number(f.get('setPieces')||5),secondarySetId:f.get('secondarySetId')||buildDraft.secondarySetId||null,tertiarySetId:f.get('tertiarySetId')||buildDraft.tertiarySetId||null,costPattern:f.get('costPattern')||'43311',stats:{...buildDraft.stats,...Object.fromEntries(buildStatSlots(buildDraft).map(([k])=>[k,f.get(k)||null]))},substats:EchoRules.subTypes.filter(k=>f.get('sub:'+k)==='on'),notes:f.get('notes')};
}
Object.assign(companionActions,{
 'edit-team':id=>{teamOriginal=CompanionStore.get().teams.find(t=>t.id===id);if(!teamOriginal)return;teamDraft=structuredClone(teamOriginal);render();document.getElementById('teamForm')?.scrollIntoView({block:'center'});},
 'cancel-team':()=>{teamDraft=null;teamOriginal=null;render();},
 'favorite-team':id=>{CompanionStore.update(s=>{const t=s.teams.find(t=>t.id===id);if(t)t.favorite=!t.favorite;},tr('Favori actualisé','Favorite updated'));render();},
 'remove-team':id=>{if(!confirm(tr('Retirer cette équipe ?','Remove this team?')))return;CompanionStore.update(s=>{s.teams=s.teams.filter(t=>t.id!==id);},tr('Équipe retirée','Team removed'));if(teamDraft?.id===id){teamDraft=null;teamOriginal=null;}render();},
 'new-build':id=>{buildOriginal=null;buildDraft={id:crypto.randomUUID(),characterId:id,name:'',role:'dps',context:'',notes:'',weaponId:null,echoId:null,setId:null,stats:{},substats:[]};renderProfileSection();document.getElementById('buildForm')?.scrollIntoView({block:'start'});},
 'edit-build':id=>{buildOriginal=CompanionStore.get().builds.find(b=>b.id===id);if(!buildOriginal)return;buildDraft=structuredClone(buildOriginal);renderProfileSection();document.getElementById('buildForm')?.scrollIntoView({block:'start'});},
 'cancel-build':()=>{buildDraft=null;buildOriginal=null;renderProfileSection();},
 'remove-build':id=>{if(!confirm(tr('Retirer ce profil et ses liens dans les équipes ?','Remove this profile and its team links?')))return;CompanionStore.update(s=>{s.builds=s.builds.filter(b=>b.id!==id);for(const t of s.teams)for(const c of Object.keys(t.builds||{}))if(t.builds[c]===id)t.builds[c]=null;},tr('Profil retiré','Profile removed'));if(buildDraft?.id===id){buildDraft=null;buildOriginal=null;}renderProfileSection();}
});
moreViews.teams=teamsPage;
document.addEventListener('input',event=>{if(event.target.form?.id==='teamForm')teamDraft=readTeamForm(event.target.form);if(event.target.form?.id==='buildForm')try{buildDraft=readBuildForm(event.target.form);}catch{/* A partially typed weapon name remains in the form until valid. */}});
document.addEventListener('change',event=>{if(event.target.form?.id==='teamForm'&&event.target.name.startsWith('member:')){teamDraft=readTeamForm(event.target.form);for(const id of Object.keys(teamDraft.builds))if(!CompanionStore.get().builds.some(b=>b.id===teamDraft.builds[id]&&b.characterId===id))teamDraft.builds[id]=null;render();}});
document.addEventListener('submit',event=>{
 if(event.target.id==='teamSearch'){event.preventDefault();const f=new FormData(event.target);teamQuery=f.get('query');onlyFavoriteTeams=f.get('favorites')==='on';render();}
 if(event.target.id==='teamForm'){event.preventDefault();try{const t=readTeamForm(event.target);if(!t.name)throw Error('Missing name');CompanionStore.saveTeam(t,teamOriginal,tr('Équipe enregistrée','Team saved'),DATA);teamDraft=null;teamOriginal=null;render();}catch{companionMessage(tr('Équipe non enregistrée : choisis trois Résonateurs possédés distincts, ou annule pour recharger une version plus récente.','Team not saved: choose three different owned Resonators, or cancel to reload a newer version.'),true);}}
 if(event.target.id==='buildForm'){event.preventDefault();try{const b=readBuildForm(event.target,true);delete b.weaponText;CompanionStore.saveBuild(b,buildOriginal,{characters:DATA,weapons:WEAPONS},tr('Profil enregistré','Profile saved'));buildDraft=null;buildOriginal=null;renderProfileSection();}catch{companionMessage(tr('Profil non enregistré : vérifie l’arme, les statistiques (5 au maximum), le stockage ou une modification récente.','Profile not saved: check the weapon, substats (at most 5), storage or a recent change.'),true);}}
});
document.addEventListener('catalogue-ready',event=>{if(event.detail==='echo'&&buildDraft&&document.getElementById('buildForm')){
 // Refresh only catalogue selectors, preserving all text fields and focus.
 const source=document.createElement('template');source.innerHTML=buildProfilesHTML(DATA.find(c=>c.id===buildDraft.characterId));
 for(const name of ['echoId','setId','secondarySetId','tertiarySetId']){const target=document.querySelector(`#buildForm [name="${name}"]`),fresh=source.content.querySelector(`[name="${name}"]`);if(target&&fresh)target.replaceChildren(...fresh.childNodes);}
}});

document.addEventListener('change',e=>{if(e.target.form?.id==='buildForm'&&['setPieces','costPattern'].includes(e.target.name)){buildDraft=readBuildForm(e.target.form);renderProfileSection();document.querySelector('#buildForm [name="'+e.target.name+'"]')?.focus();}});
