'use strict';
let wishQuery='';
function wishlistPage(){
 const s=CompanionStore.get(),list=DATA.filter(c=>s.wishlist.includes(c.id)&&c.name.toLowerCase().includes(wishQuery.toLowerCase()));
 return companionPanel(tr('Souhaits','Wishlist'),`<p>${tr('Ajoute des Résonateurs depuis leur fiche dans l’Encyclopédie. Un souhait ne crée aucune tâche. Le pré-farm s’active uniquement avec le bouton dédié, pour un Résonateur non possédé.','Add Resonators from their Encyclopedia profile. A wish creates no tasks. Pre-farming starts only through the dedicated button, for an unowned Resonator.')}</p><form id="wishSearch" class="companion-form"><label>${tr('Rechercher','Search')}<input type="search" name="query" value="${esc(wishQuery)}"></label><button class="companion-button">${tr('Rechercher','Search')}</button></form><div class="companion-list">${list.map(c=>{const owned=s.roster?.includes(c.id);return `<article class="companion-card"><div>${c.image?`<img src="${esc(c.image)}" alt="" loading="lazy">`:'◇'}</div><div><h3>${esc(c.name)}</h3><p>${owned?tr('Possédé','Owned'):tr('Non possédé','Not owned')}${s.goals[c.id]?.prefarm&&!owned?' · '+tr('Pré-farm préparé','Pre-farming planned'):''}</p><div class="companion-actions">${companionButton('wish-profile',tr('Fiche','Profile'),c.id)}${owned?companionButton('wish-plan',tr('Améliorer','Improve'),c.id):companionButton('start-prefarm',tr('Préparer un pré-farm','Prepare pre-farming'),c.id)}${companionButton('wish-pulls',tr('Préparer mes invocations','Plan my pulls'),c.id)}${companionButton('remove-wish',tr('Retirer','Remove'),c.id)}</div></div></article>`;}).join('')||`<p>${tr('Aucun souhait correspondant.','No matching wishes.')}</p>`}</div>`)+companionPanel(tr('Souhaits et progression','Wishes and progression'),`<p>${tr('Le pré-farm utilise un départ explicite au niveau 1, ascension 0, compétences 1 et passifs verrouillés. Il ne modifie jamais la progression réelle. Les besoins restent consultatifs ; aucun stock n’est dépensé automatiquement.','Pre-farming explicitly starts at level 1, ascension 0, skills 1 and locked passives. It never changes actual progression. Costs are advisory; stock is never spent automatically.')}</p>`);
}
moreViews.wishes=wishlistPage;
Object.assign(companionActions,{
 'wish-profile':id=>openProfile('character',id),
 'wish-plan':id=>{planningCharacter=id;currentView='planner';render();},
 'start-prefarm':id=>{const s=CompanionStore.get();if(s.roster?.includes(id)||!s.wishlist.includes(id))return;goalDrafts.set(id,{...(s.goals[id]||{level:null,skills:{},priorities:{},forteNodes:{}}),prefarm:true});planningCharacter=id;currentView='planner';render();},
 'remove-wish':id=>{CompanionStore.update(s=>{s.wishlist=s.wishlist.filter(x=>x!==id);});render();},
 'wish-pulls':id=>{const s=CompanionStore.get(),owned=s.roster?.includes(id);pullDraft={...(s.settings.pullBudget||{weapons:0,characterPity:null,weaponPity:null,guaranteed:null}),characters:1};pullTarget={currentSequence:owned?(s.characters[id]?.sequence??''):-1,targetSequence:owned?Math.min(6,(s.characters[id]?.sequence??0)+1):0,currentRank:'',targetRank:0};moreTab='tracker';render();companionMessage(owned?tr('Budget préparé pour une copie supplémentaire. Ajuste le nombre pour ta séquence cible.','Budget prepared for one additional copy. Adjust the count for your target sequence.'):tr('Budget préparé pour obtenir ce Résonateur à S0. Ajuste le nombre pour une autre séquence.','Budget prepared to obtain this Resonator at S0. Adjust the count for another sequence.'));}
});
document.getElementById('view').addEventListener('submit',e=>{if(e.target.id!=='wishSearch')return;e.preventDefault();wishQuery=new FormData(e.target).get('query').trim();render();});
