const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const {startServer,seedPage,root}=require('./support.cjs');
(async()=>{const {server,base}=await startServer(),browser=await chromium.launch({headless:true,channel:'msedge'});
try{for(const lang of ['fr','en']){
 const ctx=await browser.newContext({viewport:{width:720,height:1100},serviceWorkers:'block'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await seedPage(page,lang);await page.goto(base);await page.locator('.res-row').first().waitFor();
 const nav=async view=>page.locator(`[data-view="${view}"]:visible`).click(),section=async key=>{await nav('more');await page.locator(`[data-action="more-tab"][data-value="${key}"]`).click();};
 await section('tracker');await page.waitForFunction(()=>trackerAccounts!==null);const raw={playerId:'TEST ONLY',version:'0.0.2',siteVersion:'v4.7.19',pulls:Array.from({length:10},(_,i)=>({cardPoolType:1,qualityLevel:i===0?5:3,resourceId:i===0?1413:null,name:i===0?'Qingxiao':'Test weapon',time:'2026-09-10T00:00:00Z'}))};
 const upload=async data=>page.locator('#trackerFile').setInputFiles({name:'test-export.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
 await upload(raw);await page.locator('[data-action="apply-tracker"]').click();await page.waitForFunction(()=>trackerAccounts?.[0]?.rows.length===10);assert.equal(await page.evaluate(()=>CompanionStore.get().roster.length),4);
 await upload(raw);await page.locator('[data-action="apply-tracker"]').click();await page.waitForFunction(()=>trackerPending===null);assert.equal(await page.evaluate(()=>trackerAccounts[0].rows.length),10);
 const before=await page.evaluate(()=>CompanionStore.get().characters);await page.evaluate(()=>CompanionStore.update(s=>{s.resources['3']=100;}));await upload({id:'test-profile',version:1,items:[{id:3,value:500},{id:50002,value:10}],achievements:[100],todos:[]});await page.locator('[data-action="apply-tracker"]').click();await page.waitForFunction(()=>trackerPending===null);assert.equal(await page.evaluate(()=>CompanionStore.get().resources['3']),100);assert.equal(await page.evaluate(()=>CompanionStore.get().resources['50002']),10);
 await upload({id:'test-profile',version:1,items:[{id:3,value:500}],achievements:[],todos:[]});await page.locator('#trackerReplace').check();await page.evaluate(()=>CompanionStore.update(s=>{s.resources['3']=101;}));await page.locator('[data-action="apply-tracker"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().resources['3']),101,'Reject stale import');await page.locator('[data-action="cancel-tracker"]').click();
 const budget=page.locator('#pullBudgetForm');await budget.locator('[name="characters"]').fill('1');await budget.locator('[name="weapons"]').fill('1');await budget.locator('[name="characterPity"]').fill('79');await budget.locator('[name="weaponPity"]').fill('79');await budget.locator('[name="guaranteed"]').selectOption('true');await budget.locator('button:not([type="button"])').click();assert.equal(await page.locator('.budget-grid b').last().innerText(),'2');
 await page.locator('[data-action="pull-wallet"]').click();assert.equal(await page.locator('#resourcesForm input').count(),3);
 await page.evaluate(()=>CompanionStore.update(s=>{s.wishlist.push('resonator:4');}));await section('wishes');await page.locator('[data-action="start-prefarm"]').click();const goal=page.locator('#goalForm');assert.equal(await goal.locator('output').innerText(),'1');await goal.locator('[name="level"]').fill('20');await goal.locator('[name="ascension"]').selectOption('0');await goal.locator('[value="activate"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().goals['resonator:4'].prefarm),true);assert.equal(await page.evaluate(()=>CompanionStore.get().active),null);assert.deepEqual(await page.evaluate(()=>CompanionStore.get().characters),before);
 await section('tracker');for(const width of [320,720,1152]){await page.setViewportSize({width,height:1000});assert.equal(await page.locator('#view').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(lang==='fr')await page.screenshot({path:path.join(root,`test-results/convenes-${width}.png`)});}
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-action="export-pulls"]').click();const download=await downloadPromise;const file=path.join(root,'test-results/pulls-export-'+lang+'.json');await download.saveAs(file);assert.equal(JSON.parse(require('fs').readFileSync(file,'utf8')).accounts[0].rows.length,10);
 await page.reload();await section('tracker');await page.waitForFunction(()=>trackerAccounts?.[0]?.rows.length===10);assert.deepEqual(errors,[]);await ctx.close();
}console.log('PASS: FR/EN history preview/merge/reimport/export/reload, profile conflicts, unknown wallet, budget, explicit isolated pre-farming and responsive layouts.');}
finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
