const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),detail=require('./fixtures/qingxiao-costs.json'),weaponDetail=require('./fixtures/sword-costs.json');
const chars=Array.from({length:55},(_,i)=>({id:`resonator:${i?i:1413}`,gameId:String(i?i:1413),name:i?'Test '+i:'Qingxiao',rarity:5,weapon:'Sword',element:'Aero',image:''}));
const weapons=Array.from({length:120},(_,i)=>({id:`weapon:${i?i:21010016}`,gameId:String(i?i:21010016),name:i?'Weapon '+i:'Test Sword',rarity:5,type:'Sword',image:''}));
const items={itemList:[{Id:2,Name:'Shell Credit',TypeName:'Currency'},...Array.from({length:70},(_,i)=>({Id:43010001+i,Name:'Material '+i,TypeName:'Material'}))]};
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(b);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,channel:'msedge'});
 try{for(const language of ['fr','en']){
  const context=await browser.newContext({viewport:{width:720,height:1122},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',route=>{const u=route.request().url(),p=u.endsWith('/item')?items:u.includes('/character/')?detail:u.includes('/weapon/')?weaponDetail:{GameVer:'test',ResVer:'test'};return route.fulfill({contentType:'application/json',body:JSON.stringify(p)});});
  await page.addInitScript(({chars,weapons,language,detail})=>{if(localStorage.getItem('test-seeded'))return;localStorage.setItem('test-seeded','1');localStorage.setItem('wwc_lang',language);localStorage.setItem('wwc_owned_ids','["resonator:1413"]');localStorage.setItem('wwc_account_data',JSON.stringify({Qingxiao:{level:80,ascension:5,skills:{Intro:3},forteNodes:{'node:988':false}}}));localStorage.setItem('wwc_catalog_canonical_v050',JSON.stringify({characters:chars,weapons,state:{gameVersion:'test',resourceVersion:'test'}}));localStorage.setItem('wwc_character_detail_v4:1413',JSON.stringify({gameVersion:'test',detail}));},{chars,weapons,language,detail});
  await page.goto(base);await page.locator('.res-row').waitFor();await page.evaluate(()=>CompanionStore.update(s=>{s.weapons=[{id:'copy',catalogId:'weapon:21010016',name:'Test Sword',level:80,ascension:5,rank:1}];s.characters['resonator:1413'].weaponCopyId='copy';}));
  const nav=async view=>page.locator(`[data-view="${view}"]:visible`).click();
  const resources=async()=>{await nav('account');await page.locator('#accountTabs button[onclick*="resources"]').click();await page.locator('#resourcesForm input').first().waitFor();};
  await nav('planner');const goal=page.locator('#goalForm');await goal.locator('[name="level"]').fill('90');await goal.locator('[name="ascension"]').selectOption('6');await goal.locator('[name="weaponLevel"]').fill('90');await goal.locator('[name="weaponAscension"]').selectOption('6');await goal.locator('[name="skill:4"]').fill('7');await goal.locator('[name="priority:4"]').selectOption('3');await goal.locator('[name="passive:node:988"]').check();await goal.locator('[value="activate"]').click();
  await page.waitForFunction(()=>{const c=planCharacter(),g=CompanionStore.get().goals[c.id];return currentCostPlan(c,g).complete;});
  assert.equal(await page.evaluate(()=>CompanionStore.get().active),'resonator:1413');assert.equal(await page.evaluate(()=>CompanionStore.get().characters['resonator:1413'].level),80);assert.ok(await page.locator('#planCosts .companion-card').count()>5);
  // Unsaved goal survives navigation and editing the actual character.
  await goal.locator('[name="skill:4"]').fill('8');await nav('daily');await nav('planner');assert.equal(await goal.locator('[name="skill:4"]').inputValue(),'8');await goal.locator('[value="keep"]').click();
  await resources();await page.locator('[name="item:2"]').fill('0');await page.locator('#resourceSearch [name="query"]').fill('Material 0');await page.locator('#resourceSearch button').click();await page.locator('[name="item:43010001"]').fill('100');await page.locator('#resourcesForm button:not([type="button"])').click();
  assert.deepEqual(await page.evaluate(()=>CompanionStore.get().resources),{'2':0,'43010001':100});
  await page.locator('[name="item:43010001"]').fill('101');await page.evaluate(()=>CompanionStore.update(s=>{s.resources['43010001']=99;}));await page.locator('#resourcesForm button:not([type="button"])').click();assert.equal(await page.evaluate(()=>CompanionStore.get().resources['43010001']),99,'Stale stock refuses overwrite');assert.equal(await page.locator('[name="item:43010001"]').inputValue(),'101');await page.locator('[data-action="cancel-resources"]').click();
  await nav('daily');await page.locator('[data-action="waveplate-advice"]').click();await page.locator('#waveplateAdvice p').first().waitFor();assert.match(await page.locator('#waveplateAdvice').innerText(),/Shell Credit/);
  await nav('planner');await goal.locator('[name="level"]').fill('85');await page.evaluate(()=>CompanionStore.update(s=>{s.goals['resonator:1413'].level=89;}));await goal.locator('[value="activate"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().goals['resonator:1413'].level),89,'Stale goal refuses overwrite');
  await page.locator('[data-action="cancel-goal"]').click();assert.equal(await goal.locator('[name="level"]').inputValue(),'89');await page.evaluate(()=>{document.getElementById('companionMessage')?.remove();window.scrollTo(0,0);});
  for(const width of [320,720,1152]){await page.setViewportSize({width,height:900});assert.equal(await page.locator('#view').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(language==='fr')await page.screenshot({path:path.join(root,`test-results/planner-${width}.png`)});}
  assert.deepEqual(errors,[]);await context.close();
 }console.log('PASS: FR/EN real cost plan, weapon/passive goals, drafts across navigation, stock search, unknown/zero, stale goals/stocks, daily advice and responsive layouts.');}
 finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
