const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const {startServer,seedPage,root}=require('./support.cjs');
(async()=>{const {server,base}=await startServer(),browser=await chromium.launch({headless:true,channel:'msedge'});
try{for(const lang of ['fr','en']){
 const context=await browser.newContext({viewport:{width:720,height:1122},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await seedPage(page,lang);
 let detailRequests=0;await page.route('**/character/1413',route=>{detailRequests++;return route.fulfill({contentType:'application/json',body:JSON.stringify(require('./fixtures/qingxiao-profile-'+lang+'.json'))});});
 await page.goto(base);await page.locator('.res-row').first().waitFor();const nav=async view=>page.locator(`[data-view="${view}"]:visible`).click();
 await nav('ency');await page.locator('#q').fill('Qingxiao');await page.locator('.char-card').click();await page.waitForFunction(()=>!!profileSources.get(profileKey(profileSelection))?.data);
 assert.equal(await page.locator('#profileName').innerText(),'Qingxiao');assert.equal(await page.locator('#detail').evaluate(d=>d.contains(document.activeElement)),true);
 await page.locator('[data-action="profile-tab"][data-value="skills"]').click();await page.locator('.kit-skill summary').first().click();assert.match(await page.locator('.kit-skill').first().innerText(),lang==='fr'?/cordes/:/Strings/);
 const calls=detailRequests;await page.locator('[data-action="profile-tab"][data-value="sequence"]').click();assert.equal(await page.locator('.kit-skill').count(),2);
 await page.locator('[data-action="profile-tab"][data-value="build"]').click();await page.waitForFunction(()=>!!recommendationData);assert.ok(await page.locator('.weapon-ranking li').count()>8);assert.equal(detailRequests,calls);
 await page.locator('[data-action="new-build"]').click();const form=page.locator('#buildForm');await form.locator('[name="name"]').fill('Tower profile');await form.locator('[name="context"]').fill('Boss');await form.locator('[name="weapon"]').fill('Test Sword · #weapon:21010016');await form.locator('[name="main4"]').selectOption('critRate');await form.locator('[name="sub:energy"]').check();await form.locator('[name="notes"]').fill('<img src=x onerror=alert(1)> & notes');await form.locator('button:not([type="button"])').click();
 const build=await page.evaluate(()=>CompanionStore.get().builds[0]);assert.equal(build.name,'Tower profile');assert.equal(build.weaponId,'weapon:21010016');assert.deepEqual(await page.evaluate(()=>CompanionStore.get().characters),{});assert.equal(await page.locator('#profileSection img[onerror]').count(),0,'Notes remain text');
 await page.locator('[data-action="edit-build"]').click();await form.locator('[name="name"]').fill('Draft');await page.locator('[data-action="profile-tab"][data-value="overview"]').click();await page.locator('[data-action="profile-tab"][data-value="build"]').click();assert.equal(await form.locator('[name="name"]').inputValue(),'Draft');await page.locator('[data-action="cancel-build"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().builds[0].name),'Tower profile');
 for(const width of [320,720,1152]){await page.setViewportSize({width,height:900});assert.equal(await page.locator('#detail').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(lang==='fr'){await page.locator('#detail').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(root,`test-results/profile-${width}.png`)});}}
 await page.keyboard.press('Escape');assert.equal(await page.locator('#detail').evaluate(d=>d.open),false);await nav('more');await page.locator('[data-action="more-tab"][data-value="teams"]').click();const team=page.locator('#teamForm');
 await team.locator('[name="name"]').fill('Team A');await team.locator('[name="member:0"]').selectOption('resonator:1413');await team.locator('[name="member:1"]').selectOption('resonator:1');await team.locator('[name="member:2"]').selectOption('resonator:2');await team.locator('[name="build:0"]').selectOption(build.id);await team.locator('button:not([type="button"])').click();
 assert.equal(await page.locator('.team-card').count(),1);assert.equal(await page.evaluate(id=>CompanionStore.get().teams[0].builds['resonator:1413']===id,build.id),true);await page.locator('[data-action="favorite-team"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().teams[0].favorite),true);
 await page.locator('[data-action="edit-team"]').click();await team.locator('[name="member:2"]').selectOption('resonator:1');await team.locator('button:not([type="button"])').click();assert.equal(await page.evaluate(()=>CompanionStore.get().teams[0].members[2]),'resonator:2','Duplicates rejected');await page.locator('[data-action="cancel-team"]').click();
 await page.locator('[data-action="edit-team"]').click();await team.locator('[name="name"]').fill('Stale');await page.evaluate(()=>CompanionStore.update(s=>{s.teams[0].name='Newer';}));await team.locator('button:not([type="button"])').click();assert.equal(await page.evaluate(()=>CompanionStore.get().teams[0].name),'Newer');await page.locator('[data-action="cancel-team"]').click();
 await page.locator('.team-member').first().click();await page.locator('[data-action="profile-tab"][data-value="build"]').click();await page.locator('[data-action="remove-build"]').click();assert.equal(await page.evaluate(()=>CompanionStore.get().builds.length),0);assert.equal(await page.evaluate(()=>CompanionStore.get().teams[0].builds['resonator:1413']),null);
 await page.keyboard.press('Escape');await page.reload();await nav('more');await page.locator('[data-action="more-tab"][data-value="teams"]').click();assert.equal(await page.locator('.team-card h3').innerText(),'Newer');
 for(const width of [320,720,1152]){await page.setViewportSize({width,height:900});assert.equal(await page.locator('#view').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(lang==='fr')await page.screenshot({path:path.join(root,`test-results/teams-${width}.png`)});}
 await nav('ency');await page.locator('[data-action="ency-kind"][data-value="weapon"]').click();await page.locator('#librarySearch [name="query"]').fill('Test Sword');await page.locator('#librarySearch button').click();assert.equal(await page.locator('.library-item').count(),1);
 assert.deepEqual(errors,[]);await context.close();
}console.log('PASS: bilingual real profile data, native dialog/tabs, source reuse, build drafts/save/cancel, safe notes, teams/favorites/profile references, conflicts/removal/reload and layouts.');}
finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
