const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{chromium}=require('playwright'),path=require('path');
const {startServer,seedPage,root}=require('./support.cjs');
const data=require('../data/recommendations.json'),ctx=vm.createContext({});vm.runInContext(fs.readFileSync('echo-rules.js','utf8')+';globalThis.rules=EchoRules',ctx);const rules=ctx.rules;
assert.equal(data.profiles.length,58);assert.equal(new Set(data.profiles.map(p=>p.characterId)).size,58);let count=0;
const sonatas=require('../data/sonatas.json');assert.equal(sonatas.sets.length,34);assert.match(sonatas.sets.find(s=>s.id==='3').effects[0].description.en,/Electro/);assert.doesNotMatch(sonatas.sets.find(s=>s.id==='3').effects[0].description.en,/Fusion/);for(const s of sonatas.sets)for(const e of s.effects){assert.ok(e.description.fr&&e.description.en);assert.doesNotMatch(e.description.fr+e.description.en,/\{\d+\}/);}
for(const base of data.profiles)for(const p of [base,...(base.variants||[]).map(v=>({...base,...v,stats:{...base.stats,...v.stats}}))]){
 count++;assert.equal(p.priority.length,5);assert.equal(new Set(p.priority).size,5);assert.ok(p.weapons.length);for(const [name,rank]of p.weapons){assert.ok(typeof name==='string'&&!/[<>]/.test(name));assert.ok(Number.isInteger(rank)&&rank>=1&&rank<=5);}
 for(const [slot,stats]of Object.entries(p.stats)){const allowed=rules.mainTypes(slot.startsWith('main4')?4:slot==='main1'?1:3);assert.ok(stats.length);assert.ok(stats.every(s=>allowed.includes(s)),base.characterId+': '+slot);}
 assert.ok(p.substats.length<=5&&p.substats.every(s=>rules.subTypes.includes(s)));assert.ok(p.context.fr&&p.context.en&&p.notes.fr&&p.notes.en);assert.ok([1,3,5].includes(p.setPieces||5));if((p.setPieces||5)<5)assert.ok(p.secondarySets.length);if(p.setPieces===1)assert.ok(p.tertiarySets.length);
 for(const team of p.teams){assert.equal(team.length,3);assert.equal(new Set(team).size,3);assert.ok(team.every(id=>data.coverage.characterIds.includes(id)));}
}
(async()=>{const {server,base}=await startServer(),browser=await chromium.launch({headless:true,channel:'msedge'});try{for(const lang of ['fr','en']){
 const context=await browser.newContext({viewport:{width:720,height:1000},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await seedPage(page,lang);await page.goto(base);await page.locator('.res-row').first().waitFor();
 assert.equal(await page.evaluate(()=>{localStorage.setItem(characterDetailCacheKey('1413'),JSON.stringify({gameVersion:'test',detail:{Id:999,Skills:[]}}));return readCharacterDetailCache('1413');}),null,'Wrong cache ID rejected');
 await page.evaluate(()=>{DATA.push({id:'resonator:1409',gameId:'1409',name:'Cartethyia',rarity:5,weapon:'Sword',element:'Aero',image:''},{id:'resonator:1511',gameId:'1511',name:'Lucy',rarity:5,weapon:'Pistols',element:'Spectro',image:''});extendedCatalog.echo=[{id:'e1',name:'Reminiscence - Nightmare: Adam Smasher',image:'',sets:[{id:'set1',name:'Shadow of Shattered Dreams'},{id:'set2',name:'Celestial Light'},{id:'set3',name:'Endless Resonance'}]}];openProfile('character','resonator:1409');});
 await page.locator('[data-action="profile-tab"][data-value="build"]').click();await page.waitForFunction(()=>!!recommendationData);await page.locator('[data-action="recommendation-copy"]').click();const form=page.locator('#buildForm');assert.equal(await form.locator('[name="costPattern"]').inputValue(),'44111');assert.equal(await form.locator('[name="main4b"]').inputValue(),'critDmg');assert.equal(await form.locator('[name="main3"]').count(),0);await form.locator('button:not([type="button"])').click();assert.equal(await page.evaluate(()=>CompanionStore.get().builds[0].costPattern),'44111');
 await page.evaluate(()=>openProfile('character','resonator:1511'));await page.locator('[data-action="profile-tab"][data-value="build"]').click();await page.locator('[data-action="recommendation-copy"]').click();assert.equal(await form.locator('[name="setPieces"]').inputValue(),'1');assert.equal(await form.locator('[name="secondarySetId"]').inputValue(),'set2');assert.equal(await form.locator('[name="tertiarySetId"]').inputValue(),'set3');await form.locator('button:not([type="button"])').click();assert.equal(await page.evaluate(()=>CompanionStore.get().builds[1].setPieces),1);
 await page.evaluate(()=>openProfile('character','resonator:1413'));await page.locator('[data-action="profile-tab"][data-value="build"]').click();assert.equal(await page.locator('.weapon-ranking li').count(),11);
 await page.evaluate(()=>{DATA.push({id:'resonator:1211',gameId:'1211',name:'Denia',weapon:'Rectifier',element:'Fusion',rarity:5,image:''});openProfile('character','resonator:1211');});await page.locator('[data-action="profile-tab"][data-value="build"]').click();await page.locator('[data-action="recommendation-context"][data-value="resonator:1211|1"]').click();assert.match(await page.locator('.recommendation').innerText(),/Reel of Spliced Memories|Bobine de mémoire/);assert.equal(await page.evaluate(()=>recommendationFor('resonator:1211').teams[0][0]),'resonator:1413');
 for(const width of [320,720,1152]){await page.setViewportSize({width,height:1000});assert.equal(await page.locator('#detail').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);if(lang==='fr')await page.screenshot({path:path.join(root,`test-results/recommendations-${width}.png`)});}
 await page.evaluate(()=>{extendedCatalog.echo.push({id:'6000039',name:'TEST Tempest',image:'',sets:[{id:'3',name:'Void Thunder'}]});openProfile('echo','6000039');});await page.waitForFunction(()=>!!sonataData);await page.locator('#profileSection .kit-skill').first().locator('summary').click();assert.match(await page.locator('#profileSection .kit-skill').first().innerText(),/10/);
 assert.deepEqual(errors,[]);await context.close();
}console.log('PASS: '+count+' source contexts, 58 canonical IDs, valid stats/ranks/teams, bilingual 44111 and mixed Sonata copy/save, context switching and responsive dialogs.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
